### PR TITLE
Handle masking more consistently (fix #52)

### LINKED ISSUE #52: Masked generation.
I'm running into issues trying to `samplebackward` with masked arrays. I see the method is defined, but I run into:
```julia
ERROR: MethodError: endpoint_conditioned_sample(::TaskLocalRNG, ::UniformDiscreteDiffusion{Float32}, ::Float32, ::Float32, ::Diffusions.MaskedArray{Int64, 2, Matrix{Int64}, Vector{Int64}}, ::Diffusions.MaskedArray{Int64, 2, Matrix{Int64}, Vector{Int64}}) is ambiguous.

Candidates:
  endpoint_conditioned_sample(rng::AbstractRNG, P::UniformDiscreteDiffusion, s::Real, t::Real, X0, Xt)
    @ Diffusions ~/.julia/packages/Diffusions/qqyVG/src/JC.jl:36
  endpoint_conditioned_sample(rng::AbstractRNG, process::Diffusions.Process, s::Real, t::Real, x_0::Diffusions.MaskedArray, x_t::Diffusions.MaskedArray)
    @ Diffusions ~/.julia/packages/Diffusions/qqyVG/src/interface.jl:70

Possible fix, define
  endpoint_conditioned_sample(::AbstractRNG, ::UniformDiscreteDiffusion, ::Real, ::Real, ::Diffusions.MaskedArray, ::Diffusions.MaskedArray)
```

### PR DESCRIPTION
**Pull request by bicycle1885**
This will fix #52 by introducing `_endpoint_conditioned_sample` to all diffusion types and forcing mask inheritance from x_t. I also added some tests and code cleanups. This will supersede #53.

### CODE REVIEW

**Comment by murrellb** [comment]
Does this for one of my cases, where P21 is a UniformDiscreteDiffusion, and simseq_batch is *not* masked. This doesn't happen with my PR #53:
```julia
julia> generated = samplebackward(xzero, P21, timesteps, simseq_batch)
ERROR: StackOverflowError:
Stacktrace:
     [1] endpoint_conditioned_sample(rng::TaskLocalRNG, process::UniformDiscreteDiffusion{Float32}, s::Float32, t::Float32, x_0::Int64, x_t::Int64)
       @ Diffusions ~/.julia/packages/Diffusions/fI47h/src/interface.jl:80
     [2] _broadcast_getindex_evalf(::typeof(Diffusions.endpoint_conditioned_sample), ::TaskLocalRNG, ::UniformDiscreteDiffusion{Float32}, ::Float32, ::Float32, ::Int64, ::Int64)
       @ Base.Broadcast ./broadcast.jl:683
     [3] _broadcast_getindex(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(Diffusions.endpoint_conditioned_sample), Tuple{Base.RefValue{TaskLocalRNG}, Base.RefValue{UniformDiscreteDiffusion{Float32}}, Float32, Float32, Int64, Int64}}, I::CartesianIndex{0})
       @ Base.Broadcast ./broadcast.jl:656
     [4] getindex(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(Diffusions.endpoint_conditioned_sample), Tuple{Base.RefValue{TaskLocalRNG}, Base.RefValue{UniformDiscreteDiffusion{Float32}}, Float32, Float32, Int64, Int64}}, I::CartesianIndex{0})
       @ Base.Broadcast ./broadcast.jl:610
     [5] copy(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(Diffusions.endpoint_conditioned_sample), Tuple{Base.RefValue{TaskLocalRNG}, Base.RefValue{UniformDiscreteDiffusion{Float32}}, Float32, Float32, Int64, Int64}})
       @ Base.Broadcast ./broadcast.jl:888
     [6] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(Diffusions.endpoint_conditioned_sample), Tuple{Base.RefValue{TaskLocalRNG}, Base.RefValue{UniformDiscreteDiffusion{Float32}}, Float32, Float32, Int64, Int64}})
       @ Base.Broadcast ./broadcast.jl:873
--- the last 6 lines are repeated 13329 more times ---
 [79981] endpoint_conditioned_sample(rng::TaskLocalRNG, process::UniformDiscreteDiffusion{Float32}, s::Float32, t::Float32, x_0::Int64, x_t::Int64)
       @ Diffusions ~/.julia/packages/Diffusions/fI47h/src/interface.jl:80
 [79982] _broadcast_getindex_evalf(::typeof(Diffusions.endpoint_conditioned_sample), ::TaskLocalRNG, ::UniformDiscreteDiffusion{Float32}, ::Float32, ::Float32, ::Int64, ::Int64)
       @ Base.Broadcast ./broadcast.jl:683
 [79983] _broadcast_getindex(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(Diffusions.endpoint_conditioned_sample), Tuple{Base.RefValue{TaskLocalRNG}, Base.RefValue{UniformDiscreteDiffusion{Float32}}, Float32, Float32, Int64, Int64}}, I::CartesianIndex{0})
       @ Base.Broadcast ./broadcast.jl:656
       ```

**Comment by bicycle1885** [comment]
Thank you for catching it. It was a careless mistake. I've update the PR and it should work now.

**Comment by murrellb** [comment]
Can we merge this?

**Comment by murrellb** [comment]
@bicycle1885 We might want to modify `show` to avoid this trap:
image

**Pull request merged**
